spring:
  application:
    name: User-Service
  profiles:
    active: dev
  config:
    import: application-prod.yml
  cache:
    type: redis
    cache-names: redis-cache
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false
  datasource:
    url: jdbc:postgresql://localhost:5433/stroy1click
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  flyway:
    url: jdbc:postgresql://localhost:5433/stroy1click
    user: postgres
    password: password
    baseline-on-migrate: true
  messages:
    basename: messages
    encoding: UTF-8
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      group-id: user-service
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: ru.stroy1click.common.*
  threads:
    virtual:
      enabled: true

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

redisson:
  host: 127.0.0.1
  port: 6379
  username: default
  password: password

otel:
  sdk:
    disabled: true

server:
  port: 8080

resilience4j:
  ratelimiter:
    instances:
      userLimiter:
        limitForPeriod: 100
        limitRefreshPeriod: 1s