spring:
  application:
    name: User-Service
  profiles:
    active: dev
  config:
    import: application-prod.yml
  cache:
    type: redis
    cache-names: redis-cache
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false
  datasource:
    url: jdbc:postgresql://localhost:5433/stroy1click
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  flyway:
    url: jdbc:postgresql://localhost:5433/stroy1click
    user: postgres
    password: password
    baseline-on-migrate: true
  messages:
    basename: messages
    encoding: UTF-8

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

redisson:
  host: 127.0.0.1
  port: 6379
  username: default
  password: password

otel:
  service:
    name: "user-service"
  traces:
    exporter: "otlp"
    sampler: "always_on"
  metrics:
    exporter: "otlp"
    export:
      interval: 5000
  logs:
    exporter: "otlp"
  exporter:
    otlp:
      protocol: "grpc"
      endpoint: "http://localhost:4317"

server:
  port: 8080

resilience4j:
  ratelimiter:
    instances:
      userLimiter:
        limitForPeriod: 100
        limitRefreshPeriod: 1s