create schema if not exists account;

create table if not exists account.users(
                                            id bigint generated by default as identity primary key ,
                                            first_name varchar(30) not null ,
                                            last_name varchar(30) not null ,
                                            email varchar(50) not null unique ,
                                            password varchar not null ,
                                            role varchar not null,
                                            email_confirmed boolean not null
);

create index on account.users(email);

-- Test: UserTests get()
-- Description: Get the user
insert into account.users(first_name, last_name, email, password, role, email_confirmed) values ('Mike', 'Thompson', 'mike_thompson@gmail.com', 'password123', 'ROLE_USER',false);

-- Test: UserTests update()
-- Description: Update the user
insert into account.users(first_name, last_name, email, password, role, email_confirmed) values ('Kate', 'Thompson', 'kate_thompson@gmail.com', '123password123', 'ROLE_USER', false);

-- Test: UserTests delete()
-- Description: Delete the user
insert into account.users(first_name, last_name, email, password, role, email_confirmed) values ('Jake', 'Thompson', 'jake_thompson@gmail.com', '123password123', 'ROLE_USER', false);
